### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by sawsa307**
Run `go mod tidy` and `go mod vendor`.

/assign @krzyzacy

### CODE REVIEW

**Review by krzyzacy — APPROVED** [review]

**Comment by sawsa307** [comment]
Hi @krzyzacy could you take another look and approve this PR? Thank you!

**Review by krzyzacy — APPROVED** [review]

**Comment by krzyzacy** [comment]
emmm seems I don't have root approval here

**Comment by sawsa307** [comment]
@krzyzacy Hi Sen sorry I was still updating my commits, and now it should be ready for review. Could you take a look and lgtm? Thank you!

**Pull request merged**
