### PR TITLE
Push ibmcloud-janitor-boskos image

### PR DESCRIPTION
**Pull request by mkumatag**
This PR will push the docker image for the ibmcloud-janitor-boskos

### CODE REVIEW

**Review by chaodaiG — APPROVED** [review]
I'm not quite sure whether this will work.

/hold
please monitor

**Comment by mkumatag** [comment]
> I'm not quite sure whether this will work.
> 
> /hold please monitor

In the post merge I see image is [getting built](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-boskos-push-images/1525126686041968640#1:build-log.txt%3A748) but not pushed, and per explanation [here](https://cloud.google.com/build/docs/build-config-file-schema#images) under images it will push the image built. I think it will work :)

**Comment by chaodaiG** [comment]
cool, good to know that the image was built

/unhold

**Comment by mkumatag** [comment]
> cool, good to know that the image was built
> 
> /unhold

Even I was surprised when I saw this but [Makefile](https://github.com/kubernetes-sigs/boskos/blob/1f99d9b72cc441744ee39a7d51eaecc7c6b09b66/Makefile#L74) is written really well to handle any new entry.

**Pull request merged**
