### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by ixdy**
This is a follow-on to #1.

Bazel was a pain to fix. I spent several hours fixing it (since it has image building), and now it maybe works? Fixing the go build/test was fairly trivial.

/assign @alvaroaleman @stevekuznetsov 

/hold
waiting for #1

### CODE REVIEW

**Comment by ixdy** [comment]
native go build:
```console
{0} [2158] (fix-build) ~/.../src/sigs.k8s.io/boskos $ go clean -cache
{0} [2158] (fix-build) ~/.../src/sigs.k8s.io/boskos $ go clean -testcache
{0} [2158] (fix-build) ~/.../src/sigs.k8s.io/boskos $ time make build
go build ./...

real    0m27.338s
user    3m57.869s
sys     0m18.685s
{0} [2159] (fix-build) ~/.../src/sigs.k8s.io/boskos $ time make test
go test ./...
?       sigs.k8s.io/boskos/aws-janitor  [no test files]
?       sigs.k8s.io/boskos/aws-janitor/account  [no test files]
?       sigs.k8s.io/boskos/aws-janitor/cmd/aws-janitor-boskos   [no test files]
?       sigs.k8s.io/boskos/aws-janitor/cmd/aws-resources-list   [no test files]
?       sigs.k8s.io/boskos/aws-janitor/regions  [no test files]
ok      sigs.k8s.io/boskos/aws-janitor/resources        0.121s
?       sigs.k8s.io/boskos/aws-janitor/s3       [no test files]
ok      sigs.k8s.io/boskos/cleaner      0.714s
ok      sigs.k8s.io/boskos/cleaner/v2   0.276s
ok      sigs.k8s.io/boskos/client       0.102s
?       sigs.k8s.io/boskos/cmd/boskos   [no test files]
?       sigs.k8s.io/boskos/cmd/cleaner  [no test files]
ok      sigs.k8s.io/boskos/cmd/cli      5.655s
?       sigs.k8s.io/boskos/cmd/fake-mason       [no test files]
ok      sigs.k8s.io/boskos/cmd/janitor  0.201s
?       sigs.k8s.io/boskos/cmd/metrics  [no test files]
?       sigs.k8s.io/boskos/cmd/reaper   [no test files]
ok      sigs.k8s.io/boskos/common       0.156s
?       sigs.k8s.io/boskos/common/aws   [no test files]
?       sigs.k8s.io/boskos/crds [no test files]
ok      sigs.k8s.io/boskos/handlers     0.363s
ok      sigs.k8s.io/boskos/mason        1.967s
ok      sigs.k8s.io/boskos/metrics      0.179s
ok      sigs.k8s.io/boskos/ranch        0.627s
ok      sigs.k8s.io/boskos/storage      0.041s

real    0m12.539s
user    1m34.816s
sys     0m17.127s
```

bazel:
```console
{0} [2159] (fix-build) ~/.../src/sigs.k8s.io/boskos $ bazel clean
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
{0} [2159] (fix-build) ~/.../src/sigs.k8s.io/boskos $ time make bazel-build
bazel build //...
INFO: Analyzed 80 targets (788 packages loaded, 13934 targets configured).
INFO: Found 80 targets...
INFO: From Generating Descriptor Set proto_library @go_googleapis//google/iam/v1:iam_proto:                                                 
google/iam/v1/options.proto:20:1: warning: Import google/api/annotations.proto is unused.                                                   
google/iam/v1/policy.proto:21:1: warning: Import google/api/annotations.proto is unused.
INFO: From Generating into bazel-out/k8-fastbuild/bin/external/go_googleapis/google/iam/v1/iam_go_proto_/google.golang.org/genproto/googleap
is/iam/v1:
google/iam/v1/options.proto: warning: Import google/api/annotations.proto is unused.
google/iam/v1/policy.proto: warning: Import google/api/annotations.proto is unused.
INFO: From Generating Descriptor Set proto_library @go_googleapis//google/iam/v1:iam_proto:
google/iam/v1/options.proto:20:1: warning: Import google/api/annotations.proto is unused.
google/iam/v1/policy.proto:21:1: warning: Import google/api/annotations.proto is unused.
INFO: From GoLink cmd/cleaner/cleaner_/cleaner:
link: warning: package "cloud.google.com/go/storage" is provided by more than one rule:
    @com_google_cloud_go//storage:go_default_library
    @com_google_cloud_go_storage//:go_default_library
Set "importmap" to different paths in each library.
This will be an error in the future.
INFO: From Generating into bazel-out/k8-fastbuild-ST-05b09dfdd2e5ae92d24745e4e699444f165b36fe4c5cff40bcd8e02b7f69ac79/bin/external/go_google
apis/google/iam/v1/iam_go_proto_/google.golang.org/genproto/googleapis/iam/v1:
google/iam/v1/options.proto: warning: Import google/api/annotations.proto is unused.
google/iam/v1/policy.proto: warning: Import google/api/annotations.proto is unused.
INFO: From GoLink cmd/metrics/app.binary_/app.binary:
link: warning: package "cloud.google.com/go/storage" is provided by more than one rule:
    @com_google_cloud_go//storage:go_default_library
    @com_google_cloud_go_storage//:go_default_library
Set "importmap" to different paths in each library.
This will be an error in the future.
INFO: From GoLink cmd/cleaner/app.binary_/app.binary:
link: warning: package "cloud.google.com/go/storage" is provided by more than one rule:
    @com_google_cloud_go//storage:go_default_library
    @com_google_cloud_go_storage//:go_default_library
Set "importmap" to different paths in each library.
This will be an error in the future.
INFO: From GoLink cmd/boskos/app.binary_/app.binary:
link: warning: package "cloud.google.com/go/storage" is provided by more than one rule:
    @com_google_cloud_go//storage:go_default_library
    @com_google_cloud_go_storage//:go_default_library
Set "importmap" to different paths in each library.
This will be an error in the future.
INFO: From Generating Descriptor Set proto_library @go_googleapis//google/iam/v1:iam_proto:
google/iam/v1/options.proto:20:1: warning: Import google/api/annotations.proto is unused.
google/iam/v1/policy.proto:21:1: warning: Import google/api/annotations.proto is unused.
INFO: From Generating into bazel-out/k8-fastbuild-ST-3bfd66f45e612c1a5c797474a25664e227d81bf914f3b08a40e00b2e2692afa4/bin/external/go_google
apis/google/iam/v1/iam_go_proto_/google.golang.org/genproto/googleapis/iam/v1:
google/iam/v1/options.proto: warning: Import google/api/annotations.proto is unused.
google/iam/v1/policy.proto: warning: Import google/api/annotations.proto is unused.
INFO: From GoLink cmd/metrics/metrics_/metrics:
link: warning: package "cloud.google.com/go/storage" is provided by more than one rule:
    @com_google_cloud_go//storage:go_default_library
    @com_google_cloud_go_storage//:go_default_library
Set "importmap" to different paths in each library.
This will be an error in the future.
INFO: From GoLink cmd/boskos/boskos_/boskos:
link: warning: package "cloud.google.com/go/storage" is provided by more than one rule:
    @com_google_cloud_go//storage:go_default_library
    @com_google_cloud_go_storage//:go_default_library
Set "importmap" to different paths in each library.
This will be an error in the future.
INFO: Elapsed time: 226.158s, Critical Path: 72.59s
INFO: 3264 processes: 3264 linux-sandbox.
INFO: Build completed successfully, 3492 total actions

real    3m46.192s
user    0m0.111s
sys     0m0.087s
{0} [2203] (fix-build) ~/.../src/sigs.k8s.io/boskos $ time make bazel-test
bazel test //...
INFO: Analyzed 80 targets (0 packages loaded, 0 targets configured).
INFO: Found 68 targets and 12 test targets...
INFO: Elapsed time: 6.473s, Critical Path: 6.10s
INFO: 12 processes: 12 linux-sandbox.
INFO: Build completed successfully, 13 total actions
//aws-janitor/resources:go_default_test                                  PASSED in 0.5s
//cleaner:go_default_test                                                PASSED in 0.8s
//cleaner/v2:go_default_test                                             PASSED in 0.6s
//client:go_default_test                                                 PASSED in 0.5s
//cmd/cli:go_default_test                                                PASSED in 6.1s
//cmd/janitor:go_default_test                                            PASSED in 0.6s
//common:go_default_test                                                 PASSED in 0.3s
//handlers:go_default_test                                               PASSED in 0.9s
//mason:go_default_test                                                  PASSED in 2.3s
//metrics:go_default_test                                                PASSED in 0.6s
//ranch:go_default_test                                                  PASSED in 0.8s
//storage:go_default_test                                                PASSED in 0.4s

Executed 12 out of 12 tests: 12 tests pass.
INFO: Build completed successfully, 13 total actions

real    0m6.555s
user    0m0.019s
sys     0m0.011s

**Comment by alvaroaleman** [comment]
@ixdy can you rebase? Also, do we want to keep bazel? From my understanding, it doesn't provide much value if all you want to do is `go test` and `go build`

**Comment by ixdy** [comment]
Rebased.

I eventually want to get rid of bazel, but it might be useful to keep in the short term, since we already have infrastructure to build images. (At first I thought this would be pretty easy, but it actually took a while to get working.)

I generally plan to remove the bazel support once I figure out the right infrastructure to build these images reproducibly without duplicating too much code.

**Pull request merged**
