### PR TITLE
Add Parallelstore instance support to GCP Janitor

### PR DESCRIPTION
**Pull request by uriel-guzman**
Example PR for Filestore: https://github.com/kubernetes-sigs/boskos/pull/111

### CODE REVIEW

**Comment by uriel-guzman** [comment]
cc: @msau42

**Comment by uriel-guzman** [comment]
cc @krzyzacy

**Comment by krzyzacy** [comment]
please address the comment above?

**Review by krzyzacy — COMMENTED** [review]
(oh sorry I've never send this out)

**Review by krzyzacy — APPROVED** [review]

**Pull request merged**
