### PR TITLE
Update gcloud SDK version to the latest for the janitor image

### PR DESCRIPTION
**Pull request by chizhg**
It's been two years old, so it's the time to bump it, instead of investigate any issues that are potentially related to a stale version.

/cc @krzyzacy 

FYI @chaodaiG @coryrc

### CODE REVIEW

**Review by krzyzacy — APPROVED** [review]

**Comment by chizhg** [comment]
/cc @chaodaiG 

It looks we also need to add Sen as the owner of the janitor Dockerfile.

**Comment by chaodaiG** [comment]
> /cc @chaodaiG 
> 
> It looks we also need to add Sen as the owner of the janitor Dockerfile.

Mind including in this PR? I can approve

**Comment by chizhg** [comment]
> > /cc @chaodaiG
> > It looks we also need to add Sen as the owner of the janitor Dockerfile.
> 
> Mind including in this PR? I can approve

Done.

**Pull request merged**
