### PR TITLE
Update Golang and Prow

### PR DESCRIPTION
**Pull request by danilo-gemoli**
Keep up with the recent Prow repository change to [https://github.com/kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow).
I have also bumped to Golang version to `1.22.3` to stay consistent with Prow.

### CODE REVIEW

**Comment by smg247** [comment]
@danilo-gemoli what steps did you take to generate this diff?

**Comment by danilo-gemoli** [comment]
The process wasn't straightforward but it can be summed up like so:
- bump Golang to `v1.22.3` with `go mod edit -go=1.22.3` and some other changes to the `Makefile`
- install the new Prow module: `go get sigs.k8s.io/prow@latest`
- fix the import path in accordance with these rules: https://github.com/kubernetes/test-infra/issues/31728#issuecomment-2061187723
- fix some breaking changes on the `controller-runtime` dependency. As an example:
```diff
-               Namespace:               namespace,
-               MetricsBindAddress:      "0",
+               Cache:                   cache.Options{DefaultNamespaces: map[string]cache.Config{namespace: {}}},
+               Metrics:                 server.Options{BindAddress: "0"},
```

**Pull request merged**
