### PR TITLE
Move from AWS SDK v1 to v2

### PR DESCRIPTION
**Pull request by dims**
xref: https://github.com/kubernetes-sigs/boskos/issues/196

Tested what i can in my work AWS account. I'd like to land this and watch the CI jobs for a few days for errors

### CODE REVIEW

**Comment by dims** [comment]
Example run:

[janitor.log](https://github.com/user-attachments/files/16442285/janitor.log)

**Comment by ameukam** [comment]
Nice!

/lgtm

**Review by krzyzacy — APPROVED** [review]
/lgtm

**Comment by krzyzacy** [comment]
the v1.23 tag seems wrong :-\

**Comment by dims** [comment]
> the v1.23 tag seems wrong :-\

no clue how that got added!

**Pull request merged**
